services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12345
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: